### PR TITLE
Update Shebang to make executable file more portable

### PR DESCRIPTION
**Pull request by BeatLink**
Removes hard coding of perl path in executable, making gmusicbrowser more flexible to different file and folder paths

### CODE REVIEW

**Comment by BeatLink** [comment]
Any updates on getting this merged? @squentin

**Comment by RomanHargrave** [comment]
`env` is typically located in `/usr/bin`.

**Comment by BeatLink** [comment]
hmm, fair point

**Comment by BeatLink** [comment]
ill fix it

**Comment by BeatLink** [comment]
All fixed!

**Pull request merged**
